spring.application.name=JobPortfolio


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=validate

spring.jpa.hibernate.ddl-auto=update

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${EMAIL_USER_NAME}
spring.mail.password=${EMAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#for Render
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.keepalive-time=15000

server.port=${PORT:8080}

spring.security.user.name=admin
spring.security.user.password=Admin@123

#SendGri
sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.from.email=lynkjobs09@gmail.com
sendgrid.from.name=LyNK Jobs






##spring.datasource.url=${database-1.c7g2g6ce6xmv.ap-southeast-2.rds.amazonaws.com:3306/JobPortfolio}?useSSL=false&allowPublicKeyRetrieval=true
#
#
## DATABASE (from Render ENV)
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.application.name=JobPortfolio
#
#server.port=${PORT:8080}
#
## DATABASE (Render ENV)
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#
## MAIL (Render ENV)
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
## SECURITY
#spring.security.user.name=admin
#spring.security.user.password=Admin@123
